// This is action creator function
// Action creator is the function that is usually called by event from component
// action creator is function that returns an object
// 1: write action creator (made here),
// 2: wire action creator to redux to show it up in the right place (made in reducers/index)
// 3: connect the component (container) by binding the action to component (made in containers/book-list)
// import the action creator into the component (container)
// import the function bindActionCreators from redux into the component (container)
// bindActionCreators is the function that makes action (generated by action creator) to flow throughout all the reducers of application
// bindActionCreators takse the return value from action creator and makes it flow throughout all reducers of application

export function selectBook(book) {
  // console.log('A book has been selected:', book.title);
  // selectBook is action creator function and needs to return the action object with a type property
  // actions usually have 2 values: type and payload
  // type describes the purpose of the action
  // payload clarifies conditions of the action that is being triggered
  return {
    type: 'BOOK_SELECTED', //describes the purpose of the action use string for type just for now
    payload: book // piece of data that describes the action that is being undertaken
  };
}
